### ISSUE TITLE
get eps diluted with python

### ISSUE THREAD

**Issue by machine85** [robren/quandl_fund_xlsx#3]
* quandl_xlsx_cli version: 
* Python version:
* Operating System:

Hello,

i saW your great product for getting Stock Prices,

is there is a way for get also keys ratios like eps diluted ?

regards,

Tomer

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by robren** [comment]
Hi Tomer,

Sorry for the delay in replying.

Yes, Earnings Per Share Diluted is provided. I use the epsdil  indicator from the Sharadar SF1 data set.

These values are presented in the "Sharadar Income" section of a given tickers sheet.

Regards

Rob
